import streamlit as st
from datetime import datetime

st.title("📄 Engineering Reports")

physics_sei = st.number_input(
    "Physics_SEI",
    value=1.18
)

health_score = st.number_input(
    "Health Score (%)",
    value=92.8
)

status = st.selectbox(
    "Status",
    ["Optimal", "Suboptimal"]
)

report_text = f"""
DISTILLATION INTELLIGENCE REPORT
Generated: {datetime.now()}

----------------------------------------

Physics_SEI: {physics_sei:.4f}

Health Score: {health_score:.1f}%

Operating Status: {status}

----------------------------------------

Recommendations:

1. Maintain stable FlowC1.
2. Avoid excessive temperature variation.
3. Monitor vapour pressure continuously.
4. Operate near optimized conditions.

----------------------------------------

Generated by:
Distillation Intelligence Platform
"""

st.text_area(
    "Report Preview",
    report_text,
    height=350
)

st.download_button(
    "📥 Download Report",
    report_text,
    file_name="distillation_report.txt"
)